modLoader="javafml"
loaderVersion="[47,)"
license="GPL v2"
[[mods]]
modId="tetra"
version="6.11.0"
displayName="tetra"
authors="Mickelus"
description='''Tetra revolves around modular items and attempts to blend it together with other concepts such as adventure and technology.'''

[[dependencies.tetra]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="mutil"
    mandatory=true
    versionRange="[6.2.0,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="curios"
    mandatory=false
    versionRange="[5.2.0-beta.3+1.20.1,]"
    ordering="NONE"
    side="BOTH"
